name: Sync Subtree

#注意： 都采用强制推送

on:
  push:
    branches: [ main ]  # 触发的条件
env:
  github_rep: "git@github.com:zoushucai/bpublic.git"
  gitee_rep: "git@gitee.com:zscqsmy/blogmmm.git"
  gitee_subree: "git@gitee.com:zscqsmy/zscqsmy.git"
  sub_dir: "public"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # 这里的坑太大，一定要前面的这些信息
          fetch-depth: 0
          ssh-known-hosts: ["github.com", "gitee"]

      # 显示的注释，是用来判断哪个步骤出错的
      ##### 1. 先配置 gitee 的ssh
      - name: Configure SSH and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.REPOSIT_GITEE_PRIVATE_KEY }}"
          ssh-add - <<< "${{ secrets.REPOSIT_GITHUB_PRIVATE_KEY }}"
          
      # 1.推送 gitee 主仓库
      - name: push main to gitee repository 
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          { 
            # 推送master到gitee
            git remote add gitee-origin ${{ env.gitee_rep }} && \
            echo "这里1"
          } || {
            git remote set-url gitee-origin ${{ env.gitee_rep }} 
            echo "这里2"
          }

          git push --force gitee-origin main:master

      # 2.推送 gitee 子仓库
      - name: push subtree to gitee repositoy 
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git remote add gitee-subtree ${{ env.gitee_subree }}  

          {
            # 推送子树到gitee 的另一仓库
            git push gitee-subtree `git subtree split -P ${{ env.sub_dir }}`:master --force && \
            echo "gitee 子树1"
          } || {
            git subtree split -P ${{ env.sub_dir }} -b mysubtree2 && \
            git push --force gitee-subtree mysubtree2:master && \
            echo "gitee 子树2"
          }

      # 3.推送 github 子仓库
      - name: push subtree to github repositoy 
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git remote add sub-origin ${{ env.github_rep }}
          
          {
            # 推送子树到github的另一仓库
            git push sub-origin `git subtree split -P ${{ env.sub_dir }}`:main --force && \
            echo "github 子树1"
          } || {
            git subtree split -P ${{ env.sub_dir }} -b mysubtree1
            git push --force sub-origin  mysubtree1:main
            echo "github 子树2"
          }

      - name: 4.删除ssh
        run: |
          rm -rf ~/.ssh
          rm -rf /tmp/ssh_agent.sock
