name: Sync Subtree

#注意： 都采用强制推送

on:
  push:
    branches: [ main ]  # 触发的条件
env:
  github_rep: "git@github.com:zoushucai/bpublic.git"
  gitee_rep: "git@gitee.com:zscqsmy/blogmmm.git"
  gitee_subree: "git@gitee.com:zscqsmy/zscqsmy.git"
  sub_dir: "public"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # 这里的坑太大，一定要前面的这些信息
          fetch-depth: 0

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.REPOSIT_GITEE_PRIVATE_KEY }}" > ~/.ssh/reposit_gitee
          chmod 600 ~/.ssh/reposit_gitee
          echo "${{ secrets.REPOSIT_GITHUB_PRIVATE_KEY }}" > ~/.ssh/reposit_github
          chmod 600 ~/.ssh/reposit_github
          cat >>~/.ssh/config <<END
          Host gitee.com
            HostName gitee.com
            AddKeysToAgent yes
            StrictHostKeyChecking no
            IdentityFile ~/.ssh/reposit_gitee
          Host github.com
            HostName github.com
            AddKeysToAgent yes
            StrictHostKeyChecking no
            IdentityFile ~/.ssh/reposit_github
          END

      # 推送 gitee 主仓库
      - name: push main to gitee repository 
        run: |
          { 
            # 推送master到gitee
            git remote add gitee-origin ${{ env.gitee_rep }} && \
            echo "这里1"
          } || {
            git remote set-url gitee-origin ${{ env.gitee_rep }} 
            echo "这里2"
          }

          git push --force gitee-origin main:master

      # 推送 gitee 子仓库
      - name: push subtree to gitee repositoy 
        run: |
          git remote add gitee-subtree ${{ env.gitee_subree }}  

          {
            # 推送子树到gitee 的另一仓库
            git push gitee-subtree `git subtree split -P ${{ env.sub_dir }}`:master --force && \
            echo "gitee 子树1"
          } || {
            git subtree split -P ${{ env.sub_dir }} -b mysubtree2 && \
            git push --force gitee-subtree mysubtree2:master && \
            echo "gitee 子树2"
          }

      # 推送 github 子仓库
      - name: push subtree to github repositoy 
        run: |
          git remote add sub-origin ${{ env.github_rep }}
          
          {
            # 推送子树到github的另一仓库
            git push sub-origin `git subtree split -P ${{ env.sub_dir }}`:main --force && \
            echo "github 子树1"
          } || {
            git subtree split -P ${{ env.sub_dir }} -b mysubtree1
            git push --force sub-origin  mysubtree1:main
            echo "github 子树2"
          }

      - name: 删除ssh
        run: |
          rm -rf ~/.ssh